#!/usr/bin/env bash

sudo apt update
sudo apt install -y nginx
echo 'server_tokens off;
more_set_headers "X-Served-By: $hostname";' | sudo tee /etc/nginx/conf.d/custom_headers.conf
sudo systemctl restart nginx
