#!/usr/bin/env bash
#bsh script displays To infinity and beyond indefinitely with sleep 2,
#when receiving a SIGTERM doing I am invincible!!!,
trap "echo 'I am invincible!!!'" SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
