#!/usr/bin/env bash
#from 1 to 20 use while and case
p=1
while ((p <= 20))
do
	echo "$p"
	case $p in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((p++))
done
